[build]
  command = "npm install && npm run build"
  functions = "functions"
[template.environment]
  XERO_CLIENT_ID = "your client id"
  XERO_CLIENT_SECRET = "your client secret"
[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/server/callback?code=:code"
  query = {code = ":code", scope = ":scope", session_state = ":session_state" }
