[build]
  command = "npm install && npm run build"
  functions = "functions"
[template.environment]
  XERO_CLIENT_ID = "your client id"
  XERO_CLIENT_SECRET = "your client secret"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/callback"
